name: flutter_bloc_list_manager
version: 0.1.0
description: >
  Extension to flutter_bloc that handles the underlying logic to filter and search list view data dynamically.
homepage: https://github.com/danahartweg/flutter_bloc_list_manager

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^3.0.0
  equatable: ^1.1.0
  flutter_bloc: ^3.2.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^4.0.0
  effective_dart: ^1.2.0
  mockito: ^4.1.1
