name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.x
        with:
          flutter-version: "1.17.x"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze lib test
      - name: Test
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: Code coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.x
