name: Release and publish to pub.dev

on:
  pull_request:
    types: [opened, reopened, synchronize]

# Commented out to check the workflow without actually merging.
# on:
#   push:
#     branches:
#       - main

jobs:
  release_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # We want to verify we should publish (meaning we've bumped the package version)
      # before generating the changelog and actually publishing.
      - name: Compare package versions
        id: version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: pubspec.yml
          local_version: version
        run: |
          GLOBAL_RESULT=`flutter pub global activate --no-executables flutter_bloc_list_manager`
          echo ::set-env name=remote_version::$(echo $GLOBAL_RESULT | sed -rn 's/^Activated flutter_bloc_list_manager (.*).$/\1/p')
        env:
          formatted_local_version: v${{ steps.version.outputs.local_version }}

      - uses: andymckay/cancel-action@0.2
        if: ${{ steps.version.outputs.local_version == steps.version.outputs.remote_version }}

      - name: Parse changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v1.3.1
        with:
          version: ${{ steps.version.outputs.formatted_local_version }}
          path: ./CHANGELOG.md

      - name: Release
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.formatted_local_version }}
          release_name: ${{ steps.version.outputs.formatted_local_version }}
          draft: true
          prerelease: false
          body: ${{ steps.changelog.outputs.log_entry }}

      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          dryRunOnly: true
          skipTests: true
          accessToken: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}
