name: Release and publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  release_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.x'
          channel: 'stable'

      - name: Parse local version
        id: local_version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ./pubspec.yaml
          version: version

      - name: Parse remote version
        id: remote_version
        shell: bash
        run: |
          GLOBAL_RESULT=`flutter pub global activate --no-executables flutter_bloc_list_manager`
          echo ::set-output name=version::$(echo $GLOBAL_RESULT | grep -zoP 'Activated flutter_bloc_list_manager\s\K(.*)' | rev | cut -c 2- | rev)

      - name: Parse changelog
        if: ${{ steps.local_version.outputs.version != steps.remote_version.outputs.version }}
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.local_version.outputs.version }}
          path: ./CHANGELOG.md
        env:
          test: ${{ steps.remote_version.outputs.version }}

      - name: Release
        if: ${{ steps.local_version.outputs.version != steps.remote_version.outputs.version }}
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.local_version.outputs.version }}
          release_name: v${{ steps.local_version.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Publish
        if: ${{ steps.local_version.outputs.version != steps.remote_version.outputs.version }}
        uses: k-paxian/dart-package-publisher@v1.2
        with:
          skipTests: true
          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
